name: Push to Dockerhub

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          DEFAULT_BRANCH: main
          DEFAULT_BUMP: patch
          WITH_V: true
          DRY_RUN: true

      - name: Login to Docker Hub
        if: steps.version_bump.outputs.new_tag != steps.version_bump.outputs.old_tag
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        if: steps.version_bump.outputs.new_tag != steps.version_bump.outputs.old_tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.version_bump.outputs.new_tag }}

      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          DEFAULT_BRANCH: main
          DEFAULT_BUMP: patch
          WITH_V: true
      
      - name: Docker Hub Description
        if: success() && github.ref == 'refs/heads/main' 
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: tobvor/ddns-servercow
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
